In [58]:
import pandas as pd
import numpy as np
import math
 
first = pd.read_csv('data_house.csv').values 
length = len(first)
new = np.ones(length, dtype = float)
first =  first.astype('float')
first[:,0]=new 

train = first[range(1168),:]

test = first[range(1168,length),:]

print(train)

[[1.0000e+00 8.4500e+03 8.5600e+02 ... 3.0000e+00 1.0000e+00 2.0850e+05]
 [1.0000e+00 9.6000e+03 1.2620e+03 ... 3.0000e+00 1.0000e+00 1.8150e+05]
 [1.0000e+00 1.1250e+04 9.2000e+02 ... 3.0000e+00 1.0000e+00 2.2350e+05]
 ...
 [1.0000e+00 9.5410e+03 1.5020e+03 ... 3.0000e+00 1.0000e+00 2.3317e+05]
 [1.0000e+00 1.0475e+04 1.6940e+03 ... 3.0000e+00 1.0000e+00 2.4535e+05]
 [1.0000e+00 1.0852e+04 9.5900e+02 ... 3.0000e+00 1.0000e+00 1.7300e+05]]


In [59]:
minx1 = train[:,1].min()
maxx1 = train[:,1].max()
minx2 = train[:,2].min()
maxx2 = train[:,2].max()
minx3 = train[:,3].min()
maxx3 = train[:,3].max()
minx4 = train[:,4].min()
maxx4 = train[:,4].max()
minx5 = train[:,5].min()
maxx5 = train[:,5].max()
minx6 = train[:,6].min()
maxx6 = train[:,6].max()
minx7 = train[:,7].min()
maxx7 = train[:,7].max()

x1min = np.array([minx1 for x in range(1168)])
train[:,1] =(train[:,1] - x1min)/(maxx1-minx1)
x2min = np.array([minx2 for x in range(1168)])
train[:,2] =(train[:,2] - x2min)/(maxx2-minx2)
x3min = np.array([minx3 for x in range(1168)])
train[:,3] =(train[:,3] - x3min)/(maxx3-minx3)
x4min = np.array([minx4 for x in range(1168)])
train[:,4] =(train[:,4] - x4min)/(maxx4-minx4)
x5min = np.array([minx5 for x in range(1168)])
train[:,5] =(train[:,5] - x5min)/(maxx5-minx5)
x6min = np.array([minx6 for x in range(1168)])
train[:,6] =(train[:,6] - x6min)/(maxx6-minx6)
x7min = np.array([minx7 for x in range(1168)])
train[:,7] =(train[:,7] - x7min)/(maxx7-minx7)

x11min = np.array([minx1 for x in range(292)])
test[:,1] =(test[:,1] - x11min)/(maxx1-minx1)
x22min = np.array([minx2 for x in range(292)])
test[:,2] =(test[:,2] - x22min)/(maxx2-minx2)
x33min = np.array([minx3 for x in range(292)])
test[:,3] =(test[:,3] - x33min)/(maxx3-minx3)
x44min = np.array([minx4 for x in range(292)])
test[:,4] =(test[:,4] - x44min)/(maxx4-minx4)
x55min = np.array([minx5 for x in range(292)])
test[:,5] =(test[:,5] - x55min)/(maxx5-minx5)
x66min = np.array([minx6 for x in range(292)])
test[:,6] =(test[:,6] - x66min)/(maxx6-minx6)
x77min = np.array([minx7 for x in range(292)])
test[:,7] =(test[:,7] - x77min)/(maxx7-minx7)

xtrain = train[:,0:7]
ytrain = train[:,7].reshape(-1,1)

xtest = test[:,0:7]
ytest = test[:,7].reshape(-1,1)

print(xtest)
print(ytest)

[[1.         0.0580897  0.31167934 ... 0.40856748 0.5        0.33333333]
 [1.         0.16106943 0.51727713 ... 0.75840626 0.5        0.33333333]
 [1.         0.04010376 0.27090532 ... 0.18056195 0.375      0.33333333]
 ...
 [1.         0.03618687 0.2950933  ... 0.46199908 0.5        0.33333333]
 [1.         0.03934189 0.25708362 ... 0.17134961 0.25       0.33333333]
 [1.         0.04037019 0.31859019 ... 0.21234454 0.375      0.33333333]]
[[0.27787807]
 [0.81946952]
 [0.18900153]
 [0.17789196]
 [0.19025135]
 [0.22996806]
 [0.28343286]
 [0.34731287]
 [0.11748368]
 [0.11123455]
 [0.16664352]
 [0.08068324]
 [0.29870851]
 [0.49659769]
 [0.98611304]
 [0.11817803]
 [0.21080405]
 [0.09720872]
 [0.08346063]
 [0.31537286]
 [0.22233023]
 [0.21399806]
 [0.18483544]
 [0.19316762]
 [0.12512151]
 [0.18066935]
 [0.17094848]
 [0.19594501]
 [0.25595056]
 [0.15150674]
 [0.1987224 ]
 [0.15706152]
 [0.11269268]
 [0.22635745]
 [0.11401194]
 [0.24732676]
 [0.16469935]
 [0.32912096]
 [0.10012498]
 [0.229273

In [60]:
w = np.array([0. for x in range(7)]).reshape(-1,1)

loop = 1000000
cost = np.zeros((loop,1))
learning_rate = 0.5
for i in range(1,loop):
    r = np.dot(xtrain,w) - ytrain
    w[0] -= learning_rate*np.sum(r)/length
    cost[i] = 0.5*np.sum(r*r)/length
    w[1] -= learning_rate*np.sum(np.multiply(r, xtrain[:,1].reshape(-1,1)))/length
    w[2] -= learning_rate*np.sum(np.multiply(r, xtrain[:,2].reshape(-1,1)))/length
    w[3] -= learning_rate*np.sum(np.multiply(r, xtrain[:,3].reshape(-1,1)))/length
    w[4] -= learning_rate*np.sum(np.multiply(r, xtrain[:,4].reshape(-1,1)))/length
    w[5] -= learning_rate*np.sum(np.multiply(r, xtrain[:,5].reshape(-1,1)))/length
    w[6] -= learning_rate*np.sum(np.multiply(r, xtrain[:,6].reshape(-1,1)))/length
    if i%10000 == 0 : 
        print("gia tri cua cost:", cost[i],   "trong lan traing thu:", i)
    if i == 212000 :
        break


gia tri cua cost: [0.00151595] trong lan traing thu: 10000
gia tri cua cost: [0.00151262] trong lan traing thu: 20000
gia tri cua cost: [0.0015109] trong lan traing thu: 30000
gia tri cua cost: [0.00151002] trong lan traing thu: 40000
gia tri cua cost: [0.00150956] trong lan traing thu: 50000
gia tri cua cost: [0.00150933] trong lan traing thu: 60000
gia tri cua cost: [0.00150921] trong lan traing thu: 70000
gia tri cua cost: [0.00150915] trong lan traing thu: 80000
gia tri cua cost: [0.00150911] trong lan traing thu: 90000
gia tri cua cost: [0.0015091] trong lan traing thu: 100000
gia tri cua cost: [0.00150909] trong lan traing thu: 110000
gia tri cua cost: [0.00150909] trong lan traing thu: 120000
gia tri cua cost: [0.00150908] trong lan traing thu: 130000
gia tri cua cost: [0.00150908] trong lan traing thu: 140000
gia tri cua cost: [0.00150908] trong lan traing thu: 150000
gia tri cua cost: [0.00150908] trong lan traing thu: 160000
gia tri cua cost: [0.00150908] trong lan traing thu

In [61]:
print(w)

[[ 0.12532321]
 [ 0.10045583]
 [ 0.76425071]
 [ 0.35227675]
 [-0.15066098]
 [-0.20390034]
 [-0.27312334]]


In [67]:
denta = np.dot(xtest,w)-ytest
r = denta*denta
RMSE = math.sqrt(np.sum(r))
MAE = np.sum(abs(denta))/292
RAE = (np.sum(abs(denta)))/(np.sum(np.dot(xtest,w)))
print("gia tri RMSE:", RMSE)
print("gia tri MAE:", MAE)
print("gia tri RAE:", RAE)


gia tri RMSE: 1.440499443627054
gia tri MAE: 0.04833113656460927
gia tri RAE: 0.22699847392165184
